### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by IvanSanchez** [maydemirx/leaflet-tag-filter-button#1]
The demo has a reference to the `https` flavour of the Leaflet 0.7.7 CDN files, which never worked. Either link to the `http` files, or copy the Leaflet library files into the heroku instance.

**Comment by maydemirx** [comment]
ok. i will copy these files to my local repo

**Comment by maydemirx** [comment]
it's working now

**Comment by xiaofanwu** [comment]
The demo is not working again, but the repo seems really cool!

**Comment by maydemirx** [comment]
I could not see any problem on demo site. Can you explain the problem ?
