### ISSUE TITLE
Broken on Internet Explorer

### ISSUE THREAD

**Issue by AhmadIssa83** [maydemirx/leaflet-tag-filter-button#12]
The filter button works on Chrome and Firefox, but does not show on Internet Explorer or Internet Edge. 
Is it a button CSS/JS issue or a leaflet issue?

**Comment by maydemirx** [comment]
Yes. This is a js error. I am using ES6 string template literal in my code. But, "internet explorer" and "edge" was not support string template literals of ES6. You can see details from fallowing link: https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Template_literals

I am labeled this issue to bug and i will fix it

**Comment by AhmadIssa83** [comment]
Thank you for your quick reply. This filter is awesome and I hope this is fixed soon :)

**Comment by maydemirx** [comment]
ok i fixed the issue. you can check the demo page on ie or edge. please refresh the page because browsers can be cached older version of the library

**Comment by AhmadIssa83** [comment]
Thank you very much :)
