### ISSUE TITLE
Scrolling with the mouse does not work in Chrome/Chromium

### ISSUE THREAD

**Issue by WindohsCrasher** [maydemirx/leaflet-tag-filter-button#18]
Hi,

I have implemented your plugin into my site ( https://spalt.plus/karte ) and as you can see I have many different filter tags inside my list - too many to display them without a scrollbar. However, scrolling in that list doesn't work for me, instead the map is zooming in and out. I can only scroll by dragging the scroll bar by hand.

The issue does not exist in Firefox.

Do you have any idea what I can do to fix this behavior?

**Comment by maydemirx** [comment]
I disabled the scroll when the popup is open if the browser has no touch support. You can see the code in the source file at the line 384. But, i was see the value of the variable named as L.Browser.touch is "true" on your application. I do not know why it's value is true. Maybe you can set it's value to false before create the my plugin (L.Browser.touch = false).

**Comment by WindohsCrasher** [comment]
Thank you very much, that did the trick! :)
