### ISSUE TITLE
Assigning Tags through geoJSON and data from external JSON

### ISSUE THREAD

**Issue by schmidtster** [maydemirx/leaflet-tag-filter-button#20]
Hello, I've been running into 2 related issues with the tag filter button. The first issue is assigning tags to each of my points and the second is referencing a list of filter terms from an external JSON file through the data field.

For the first issue, this is the basic layout of my code for inserting points onto my leaflet map:
```
    var clusters = L.markerClusterGroup({maxClusterRadius:75});
    var getjson = $.getJSON("map-v2.geojson",function(data){
      var bev = L.geoJson(data,{
        pointToLayer: function(feature,latlng){
          var marker = L.marker(latlng, { tags: [feature.properties.Genres, feature.properties.Creator]});
          marker.bindPopup('<p align=center>' + '<strong>Title: </strong>' + feature.properties.Title + '<br/><a href="' + feature.properties.Image_Bank_URL + '" target="_blank"><img src="' + feature.properties.Thumbnail_URL + '"/></a><br/>' + '<strong>Date: </strong>' + feature.properties.Date + '<br/>' + '<strong>Creator: </strong>' + feature.properties.Creator, {minWidth : 250});
          return marker;
        }
      });
      clusters.addLayer(bev);
      map.addLayer(clusters);
    });
```
Essentially, where I assign var marker the value L.marker, I'm passing lat and long data being pulled from the geoJSON file, but I'm also trying to pass the genres and creator properties found in the geoJSON file as tags. From what I can tell, those data points are not being put as tags because when I copy and paste the exact tags into the L.control.tagFilterButton({ data: "" field, the markers all disappear. This is strange because it looks as though I've already set up the conditions to read from the geoJSON file via features.properties, but maybe I'm mistaken.

For the second issue, I've generated a local JSON file that has all the terms I want to use as filters for my data. I then try and get the JSON file to read the data and apply it to the data field in the L.control.tagFilterButton, just like so:

```
    var tags_json = $.getJSON("tags.json",function(data) {
      L.control.tagFilterButton({
        data: tags_json.genres,
        filterOnEveryClick: true,
        icon: '<i class="fas fa-tags"></i>',
      }).addTo(map);
```
I've tried everything from changing function(data) to function(json), assigning var tags_json as a separate variable, outside of function(data). I've even tried generating individual .txt files with just the terms to reference via jQuery, but that also does not work.

These issues might just be me failing to understand how JavaScript referencing works in this instance, in which case I apologize for cluttering the issues page with this and I'd be happy to take it down and post this in another forum. I have been searching online for any problem related to this and have found nothing. If someone is able to point me in the right direction, I'd be very grateful!

If anyone would like the html, geoJSON, and/or JSON files, I would be more than happy to share them.

And thank you for making this plugin! If I can resolve these issues, it will make my map all the more powerful and useful!

**Comment by maydemirx** [comment]
If you are getting the tags from $.getJSON you have to fetch them from "data" parameter. I can't remember $.getJSON return value. But all of Ajax should be async. When you are trying to fetch anything from the server by js you should use the callback functions and I can see you have a little bit mistake in your code. You can try use "data" parameter for the tags option.

**Comment by schmidtster** [comment]
Ah, I figured I was calling the data incorrectly! I've looked up the jQuery $.getJSON [documentation](https://api.jquery.com/jquery.getjson/), but it seems to me that I would need to fill in the data with a list of the data that I already have in my json file. This would mean that if I updated the data in my json file, I would have to manually update the values in the data parameter (something I was hoping to avoid). Would you happen to have an example of something like this working to capture any updates in the json file?
