### ISSUE TITLE
Tag with Spaces

### ISSUE THREAD

**Issue by Attiq007** [maydemirx/leaflet-tag-filter-button#23]
I am using tags with space in it. So the text after the space goes to the next line but in the same block.

How to fix it??

`
L.control.tagFilterButton({
	data: ['tomato ketchup', 'cherry blossom', 'strawberry'],
  filterOnEveryClick: true,
    icon: '<i class="fa fa-pagelines"></i>',
}).addTo( map );`
<img width="395" alt="question" src="https://user-images.githubusercontent.com/35655663/46293579-6176f480-c5ad-11e8-832b-b572e2314c21.PNG">

I want the names (tag popUps) with spaces on the same line in my project i.e. 'Tomato Ketchup' And 'Cherry Blossom'.
Please guide me.

Thanks

**Comment by maydemirx** [comment]
i will check it

**Comment by Attiq007** [comment]
Thanks for your consideration. 

I am also trying to fix it But I am kind of a newbie. But still I think something have to change in the javascript(leaflet-tag-filter-button.js) file where you use L.DomUtil.create in the  _preparePopup function. I try with some changes in my local copy of the code but nothing worked.

<img width="960" alt="question" src="https://user-images.githubusercontent.com/35655663/46342011-27602e00-c653-11e8-931c-a79ad4a09926.png">

In this inspect shows the anchor tag (a) is separated and If a tag has Space in it goes to the next line but in same "li" of the list.

I share all this so it might help you start fast.

Thanks once again.

**Comment by Attiq007** [comment]
Finally I have got the solution. But Thanks anyway.

**Comment by maydemirx** [comment]
Hello, would you like to share your solve. You can send me pull request or comment the solve.

**Comment by Attiq007** [comment]
Hi, I am glad to help you.
I simply change a module in css file.

display: inline;/*=======================    This is the problem inline-block     =================*/

instead of (display: inline-block)

That works for me.
