### ISSUE TITLE
Broken Demo

### ISSUE THREAD

**Issue by tdaubs** [maydemirx/leaflet-tag-filter-button#3]
Demo doesn't seem to be working.

**Comment by maydemirx** [comment]
Can you check again?

**Comment by tdaubs** [comment]
After a bit of testing, it seems it's more of a UI issue. Yes, the filter does work but only after you click back on the map. In my opinion, it should trigger at the moment a checkbox is selected or deselected.

**Comment by maydemirx** [comment]
"The filter should be work at the check/uncheck time" maybe this request can be new feature. This not a bug. Because filter triggered at the popup closed.

If there is no selected any checkbox then the plugin does not need filter anything.
