### ISSUE TITLE
Value checked on document ready

### ISSUE THREAD

**Issue by Wallace911** [maydemirx/leaflet-tag-filter-button#30]
Hi! There's a way to set a default value filtered at the document ready? I would like that at the end of the page load the plugin filtered a marker with a default value that I decide

**Comment by maydemirx** [comment]
There is no directly way to triggering filter by default values. But you can select checkboxes you want to and call the update method of the plugin after page load and initialized the plugin.

**Comment by Wallace911** [comment]
> 
> 
> There is no directly way to triggering filter by default values. But you can select checkboxes you want to and call the update method of the plugin after page load and initialized the plugin.

can you show me an example of code pls?

**Comment by Wallace911** [comment]
@maydemirx forgive me if I insist but I could't at select checkboxes I want. Can you show me an example?
I create a filter button this way
`var tipoPDL = L.control.tagFilterButton({
					data: ['PDL protocollati', 'PDL in previsione'],
					clearText: 'Rimuovi filtri',
					icon: '<i class="fa fa-filter"></i><span>Filtro per Tipo PDL </span>',
					filterOnEveryClick: true
				}).addTo( map );`

**Comment by maydemirx** [comment]
Hello @Wallace911  i checked the code again and i think my trick will not working. Because if the popup has no display you can not check the checkboxes programmatically. I change the issue type to feature and i will develop this feature.

**Comment by maydemirx** [comment]
@Wallace911 you can fetch the latest tagFilterButton source file from master branch. After that you can call the filter function of the plugin with array parameter that contains filter items

For example: 

filtering programmatically 

`myTagFilterButton.filter(['PDL protocollati'])`

for clear selections just call the filter function without parameter

`myTagFilterButton.filter()`

> Note: please test the feature. if you get an error or if there is a bug please open the new issue
