### ISSUE TITLE
colored tooltip

### ISSUE THREAD

**Issue by christianbleau** [maydemirx/leaflet-tag-filter-button#32]
Hi,

I use your script here https://lepetitbleausard.fr  it’s run very well. Many Thanks.

I'm looking for colored background of the tooltip for each tag \<li> on the container like yellow, red, orange, ..... 

I try to change the css of the script line 448 with <style> li:nth-child(2) {  color: #ccc; } </style> in my index.html page.

this._clearEl = L.DomUtil.create('ul', 'header', this._container);
this._clearEl.innerHTML = "\<li class='ripple'><a>" + this.options.clearText + "</a></li>";

 I try to force change the css of the  \<li> and class='ripple' , but no effect.

Many thank for your answer if you have a suggestion.

Christian Ch.

**Comment by maydemirx** [comment]
Hi, i checked your website and saw the background colors of the li items was changed. Do you have any other problem?

**Comment by christianbleau** [comment]
Hi, no thank I used a  CSS :nth-child() Selector <https://www.w3schools.com/cssref/sel_nth-child.asp> it’s work enough  for my need.

Best regards for your development.
