### ISSUE TITLE
jsDelivr has debug statement

### ISSUE THREAD

**Issue by Waffleboy** [maydemirx/leaflet-tag-filter-button#35]
The CDN @ jsDelivr loading the 0.04 version has debugger statements inside which severely impedes the use. Probably left in by mistake..?

Relevant Section
```
        hide: function(accept) {
            if (this._container && (this._container.style.display == "none" || this._container.style.display == "")) {
                return;
            }
            debugger;
            if (this._container) {
                this._container.style.display = "none";
            }
            this.filter();
            this._easyButton.button.style.display = "block";
        },

```
[Link to CDN](https://cdn.jsdelivr.net/npm/leaflet-tag-filter-button@0.0.4/src/leaflet-tag-filter-button.js)

**Comment by Waffleboy** [comment]
Hello, I'll be glad to but isn't this a CDN issue? I don't think I can replace the files on the CDN (https://www.jsdelivr.com/package/npm/leaflet-tag-filter-button)

The file in `/src` works fine, it just needs to replace the one in the CDN

**Comment by maydemirx** [comment]
:) yes you are right. i'll update as soon. thank you

**Comment by maydemirx** [comment]
Hello again. jsDelivr fetching the files from "Releases" both of npm and GitHub. Yes i removed debugger; statements from master but the last release (v0.0.4) contains debugger; And i dont know when i'll publish v0.0.5. But you can fetch the files from CDN at specific commit. Please check the [documentation](http://www.jsdelivr.com/features)

**Comment by Waffleboy** [comment]
Hello,

Thanks for this! :) Is there any reason you dont want to remove debugger from the 0.0.4 release?

**Comment by maydemirx** [comment]
Because it's already released. i do not want to edit previous release

**Comment by Waffleboy** [comment]
I understand that, but in this case, even if your previous release is unusable?

**Comment by maydemirx** [comment]
i think it is not unsable just a forgotten debugger; statement. i replied how to fix issue in my previous comments. You know this is an open source project and i try to develop this. if you want to fast reaction you can contribe to project. Please wait next release.

**Comment by Waffleboy** [comment]
Hey man, Don't get me wrong, i appreciate your work, and have even made a folium plugin for your library (https://github.com/python-visualization/folium/pull/1343).  

If i could i would submit a pull request to solve it myself, i would. I think its okay to release a 0.0.4.1 with the debugger removed, but thats your choice :)

**Comment by maydemirx** [comment]
Hi @Waffleboy,
I have released a new version of tag-filter-button. You can fetch a new sources from jsdelivr CDN
