### ISSUE TITLE
initialization with filtered result 

### ISSUE THREAD

**Issue by adhg** [maydemirx/leaflet-tag-filter-button#36]
Hi there @maydemirx ,
Is there any way to have the filter-button filter on initialization? in other words, add the layer AND filter by (not by the user). For example 'fireFilterByTag' by fast such that: 

```
myFilter = L.control.tagFilterButton({

	data: ['fast', 'slow'],
        fireFilterByTag: ['fast'], //something like this? 

}).addTo( map );
```

My Impression that this will do the trick, but it didnt:

    	myFilter .filter(['fast']);
    	myFilter .update();

**Comment by maydemirx** [comment]
if filter function doesnt work. it seems there is a bug. Can you add a little jsfiddle?

**Comment by adhg** [comment]
@maydemirx 
after I constructed my jsfiddle I realized my mistake. First thing: 
```
	myFilter.filter(['fast']);
	myFilter.update();
```
does the trick and present the right values! 

What went wrong for me? I'm using layers ( **L.layerGroup();**  ) and I should have added the layer to the map right after the markers are in the layers. 

Anyway, not a bug. The code works like a charm.

**Comment by maydemirx** [comment]
ok i'm closing the issue. by the way you don't need to call update function because filter function is already updating user interface
