### ISSUE TITLE
Small problem in demo

### ISSUE THREAD

**Issue by valerio-bozzolan** [maydemirx/leaflet-tag-filter-button#40]
I was testing the demo but I think there are some issues with the default tileserver:

https://maydemirx.github.io/leaflet-tag-filter-button/

![Screenshot_2022_02_14_160149](https://user-images.githubusercontent.com/6052909/153888686-894e3948-d15e-4e47-a311-1d71db3bb481.png)

Maybe in the demo we can adopt the default OpenStreetMap. What do you think about?

Thank you so much for your work :) Very interesting plugin. I've found it from here:

https://leafletjs.com/plugins.html

**Comment by maydemirx** [comment]
Fixed, please update the page and check again.

Thank you for your feedback.

**Comment by valerio-bozzolan** [comment]
Seems good to me! Awesome!
