### ISSUE TITLE
Tag filter on field value

### ISSUE THREAD

**Issue by valeriodeluca** [maydemirx/leaflet-tag-filter-button#6]
Hi Mehmet,

I tried your leaflet-tag-filter-button. It works fine but can I to link the tags with the field's value of json?

Like in popup mode:

var popupContent = '<table><tr><th scope="row">ID</th><td>' + (feature.properties['ID'] !== null ? Autolinker.link(String(feature.properties['ID'])) : '') + '</td></tr><tr><th scope="row">DATI</th><td>' + (feature.properties['DATI'] !== null ? Autolinker.link(String(feature.properties['DATI'])) : '') + '</td></tr><tr><th scope="row">POINT_X</th><td>' + (feature.properties['POINT_X'] !== null ? Autolinker.link(String(feature.properties['POINT_X'])) : '') + '</td></tr><tr><th scope="row">POINT_Y</th><td>' + (feature.properties['POINT_Y'] !== null ? Autolinker.link(String(feature.properties['POINT_Y'])) : '') + '</td></tr><tr><th scope="row">POINT_Z</th><td>' + (feature.properties['POINT_Z'] !== null ? Autolinker.link(String(feature.properties['POINT_Z'])) : '') + '</td></tr></table>';

I'd like use this 

(feature.properties['DATI']

for tag. 'DATI' is the field name il table of content linked json. 'DATI' is not null and can be two or more values.

I tried this:

but doesn't work.

Thanks
Valerio

**Comment by maydemirx** [comment]
How do you create a marker?

**Comment by valeriodeluca** [comment]
by QGIS plugin called QGIS2leaf.
Usually I can use feature.properties.field_name form like:

FILTER
L.geoJson(someFeatures, {
    filter: function(feature, layer) {
        return feature.properties.show_on_map;
    }
}).addTo(map);

**Comment by maydemirx** [comment]
i hope fallowing code helps you.

L.geoJson(jsonObject, {
    pointToLayer: function(feature, latlng) {
        L.marker(latlng, {
            tags: feature.properties['DATI']
        });
    }
});

**Comment by valeriodeluca** [comment]
Hi Mehmet,
tks for you suggest code.
I have this zip leaflet simple map. The countries are for zone nord, centre
and sud. Filter button is ok but I can't link the fiter to the ['zone']. I
added the shapefile.
thanks so much
best
valerio

**Comment by maydemirx** [comment]
I have edited your code and i added fallowing line to end of your pop_country function.

`layer.options.tags = [feature.properties.zone];`

And it's working.

**Comment by valeriodeluca** [comment]
tks so much man now it works very well it's true

http://vdlmap.com/leaflet-filter/

Now I just try if it works with more layer (I mean more json) with same
filter-field (the field "zone"). I'll write you
Bye
Valerio
